name: Publish Extension

on:
  push:
    tags:
      - v*

jobs:
  publish-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Package extension
        run: vsce package

      - name: Publish extension
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish -p $VSCE_TOKEN